plugins {
    id 'java'
    id 'application'
    id 'jacoco'
    id 'checkstyle'
}

group = 'com.jsonflattener'
version = '1.0.0'
sourceCompatibility = '11'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.2'
    testImplementation 'org.assertj:assertj-core:3.24.2'
}

// Фикс кодировки
tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

application {
    mainClass = 'com.jsonflattener.Main'
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacoco {
    toolVersion = "0.8.8"
}

jacocoTestCoverageVerification {
    violationRules {
        rule {
            element = 'CLASS'
            excludes = ['com.jsonflattener.Main', 'com.jsonflattener.model.*']
            limit {
                minimum = 0.75
            }
        }
    }
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = true
    }
}

// --- CHECKSTYLE (КЛАССИЧЕСКИЙ РЕЖИМ) ---
checkstyle {
    // Версия 8.45.1 работает надежнее всего при проблемах с конфигами
    toolVersion = '8.45.1'
    
    // Сборка НЕ упадет, если Checkstyle найдет ошибки (чтобы мы увидели тесты)
    ignoreFailures = true 
    // Путь к нашему файлу
    configFile = file("${rootDir}/config/checkstyle.xml")
}

// Отключаем на Windows (локально), включаем на Linux (GitHub)
if (System.getenv('CI') != 'true') {
    tasks.withType(Checkstyle) {
        enabled = false
    }
}

task runApp(type: JavaExec) {
    group = 'Application'
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'com.jsonflattener.Main'
    systemProperty "INPUT_JSON", System.getenv('INPUT_JSON') ?: 'data/input.json'
}

check.dependsOn jacocoTestCoverageVerification